# https://taskfile.dev

version: '3'
tasks:
  kind-rollout:
   - task: delete
   - task: build
   - task: kind-load
   - task: deploy
  changelog:
    cmds:
      - npx standard-version
    silent: false
  changelog-nocommit:
    cmds:
      - npx standard-version --skip.commit
    silent: false
  build:
    cmds:
      - docker build -t mathos src/
    silent: false
  kind-load:
    cmds:
      - kind load docker-image localhost/mathos:latest --name kind
    silent: false
  deploy:
    cmds:
      - kubectl apply -f src/deploy/mathos-k8s.yaml
    silent: false
  delete:
    cmds:
      - kubectl delete -f src/deploy/mathos-k8s.yaml
    silent: false