name: Mathos CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Mathos
      run: docker build ./src/backend/ --file ./src/backend/Dockerfile --tag mathos:$(date +%s)
